// prisma/seed-data.ts

export const clubs = [
  { name: "Interact Club", category: "Service", description: "Rotary-sponsored service club." },
  { name: "Beta Club", category: "Academic", description: "National academic honor society." },
  { name: "Science National Honor Society", category: "Academic", description: "STEM honor society." },
  { name: "Research Club", category: "STEM", description: "Student research and science fair prep." },
  { name: "Literary Lions Book Club", category: "Interest", description: "Student-led book club." },
  { name: "Student Council", category: "Leadership", description: "Student government and event organizing." },
  { name: "Link Crew", category: "Leadership", description: "Freshman mentorship program." },
  { name: "DECA", category: "Career", description: "Marketing and entrepreneurship." },
  { name: "Air Force JROTC", category: "Military", description: "Leadership and aerospace science." },
  { name: "Lions Pride Marching Band", category: "Arts", description: "Competitive marching band." },
  { name: "Chorus / Leo Voces", category: "Arts", description: "Vocal ensembles." },
  { name: "Strings", category: "Arts", description: "Orchestra ensemble." },
  { name: "Drama Club", category: "Arts", description: "Theatre production." },
  { name: "DWD Tech Team", category: "Technology", description: "Student technical support and media." },
];

export const sports = [
  { name: "Football", season: "Fall", gender: "Co-ed" },
  { name: "Volleyball", season: "Fall", gender: "Women's" },
  { name: "Competitive Cheer", season: "Fall", gender: "Co-ed" },
  { name: "Cross Country", season: "Fall", gender: "Co-ed" },
  { name: "Swimming", season: "Fall", gender: "Co-ed" },
  { name: "Girls Tennis", season: "Fall", gender: "Women's" },
  { name: "Girls Golf", season: "Fall", gender: "Women's" },
  { name: "Basketball (Boys)", season: "Winter", gender: "Men's" },
  { name: "Basketball (Girls)", season: "Winter", gender: "Women's" },
  { name: "Wrestling", season: "Winter", gender: "Co-ed" },
  { name: "Soccer (Boys)", season: "Spring", gender: "Men's" },
  { name: "Soccer (Girls)", season: "Spring", gender: "Women's" },
  { name: "Baseball", season: "Spring", gender: "Men's" },
  { name: "Softball", season: "Spring", gender: "Women's" },
  { name: "Track & Field", season: "Spring", gender: "Co-ed" },
  { name: "Boys Tennis", season: "Spring", gender: "Men's" },
  { name: "Boys Golf", season: "Spring", gender: "Men's" },
];

export const courses = [
  // --- ENGLISH ---
  { name: "English 1 CP", department: "English", code: "ENG-101" },
  { name: "English 1 Honors", department: "English", code: "ENG-102" },
  { name: "English 2 CP", department: "English", code: "ENG-201" },
  { name: "English 2 Honors", department: "English", code: "ENG-202" },
  { name: "English 3 CP", department: "English", code: "ENG-301" },
  { name: "English 3 Honors", department: "English", code: "ENG-302" },
  { name: "English 4 CP", department: "English", code: "ENG-401" },
  { name: "English 4 Honors", department: "English", code: "ENG-402" },
  { name: "AP English Language", department: "English", code: "ENG-501" },
  { name: "AP English Literature", department: "English", code: "ENG-502" },
  { name: "Creative Writing", department: "English", code: "ENG-ELEC-01" },
  { name: "Young Adult Literature", department: "English", code: "ENG-ELEC-02" },
  { name: "Journalism / Yearbook", department: "English", code: "ENG-ELEC-03" },

  // --- MATH ---
  { name: "Algebra 1", department: "Math", code: "MAT-101" },
  { name: "Foundations of Algebra", department: "Math", code: "MAT-100" },
  { name: "Geometry CP", department: "Math", code: "MAT-201" },
  { name: "Geometry Honors", department: "Math", code: "MAT-202" },
  { name: "Algebra 2 CP", department: "Math", code: "MAT-301" },
  { name: "Algebra 2 Honors", department: "Math", code: "MAT-302" },
  { name: "Pre-Calculus CP", department: "Math", code: "MAT-401" },
  { name: "Pre-Calculus Honors", department: "Math", code: "MAT-402" },
  { name: "Probability & Statistics", department: "Math", code: "MAT-405" },
  { name: "AP Statistics", department: "Math", code: "MAT-501" },
  { name: "AP Calculus AB", department: "Math", code: "MAT-502" },
  { name: "AP Calculus BC", department: "Math", code: "MAT-503" },

  // --- SCIENCE ---
  { name: "Physical Science", department: "Science", code: "SCI-100" },
  { name: "Biology 1 CP", department: "Science", code: "SCI-101" },
  { name: "Biology 1 Honors", department: "Science", code: "SCI-102" },
  { name: "Chemistry 1 CP", department: "Science", code: "SCI-201" },
  { name: "Chemistry 1 Honors", department: "Science", code: "SCI-202" },
  { name: "Physics", department: "Science", code: "SCI-301" },
  { name: "Anatomy & Physiology", department: "Science", code: "SCI-305" },
  { name: "Marine Science", department: "Science", code: "SCI-306" },
  { name: "Forensic Science", department: "Science", code: "SCI-307" },
  { name: "AP Biology", department: "Science", code: "SCI-501" },
  { name: "AP Chemistry", department: "Science", code: "SCI-502" },
  { name: "AP Environmental Science", department: "Science", code: "SCI-503" },
  { name: "AP Physics 1", department: "Science", code: "SCI-504" },

  // --- SOCIAL STUDIES ---
  { name: "Human Geography", department: "Social Studies", code: "SS-100" },
  { name: "World History CP", department: "Social Studies", code: "SS-101" },
  { name: "World History Honors", department: "Social Studies", code: "SS-102" },
  { name: "U.S. History CP", department: "Social Studies", code: "SS-201" },
  { name: "U.S. Government", department: "Social Studies", code: "SS-301" },
  { name: "Economics", department: "Social Studies", code: "SS-302" },
  { name: "Law Education", department: "Social Studies", code: "SS-ELEC-01" },
  { name: "Psychology / Sociology", department: "Social Studies", code: "SS-ELEC-02" },
  { name: "Current Events", department: "Social Studies", code: "SS-ELEC-03" },
  { name: "AP Human Geography", department: "Social Studies", code: "SS-501" },
  { name: "AP European History", department: "Social Studies", code: "SS-502" },
  { name: "AP U.S. History", department: "Social Studies", code: "SS-503" },
  { name: "AP U.S. Government", department: "Social Studies", code: "SS-504" },
  { name: "AP Psychology", department: "Social Studies", code: "SS-505" },

  // --- WORLD LANGUAGES ---
  { name: "Spanish 1", department: "World Language", code: "LANG-SP-101" },
  { name: "Spanish 2", department: "World Language", code: "LANG-SP-102" },
  { name: "Spanish 3 Honors", department: "World Language", code: "LANG-SP-103" },
  { name: "AP Spanish Language", department: "World Language", code: "LANG-SP-501" },
  { name: "German 1", department: "World Language", code: "LANG-GR-101" },
  { name: "German 2", department: "World Language", code: "LANG-GR-102" },
  { name: "German 3 Honors", department: "World Language", code: "LANG-GR-103" },
  { name: "AP German Language", department: "World Language", code: "LANG-GR-501" },

  // --- FINE ARTS ---
  { name: "Art 1", department: "Fine Arts", code: "ART-101" },
  { name: "Art 2", department: "Fine Arts", code: "ART-102" },
  { name: "Art 3 Honors", department: "Fine Arts", code: "ART-103" },
  { name: "AP Art: Drawing", department: "Fine Arts", code: "ART-501" },
  { name: "Band: Symphonic", department: "Fine Arts", code: "MUS-BAND-101" },
  { name: "Band: Wind Ensemble", department: "Fine Arts", code: "MUS-BAND-102" },
  { name: "Chorus", department: "Fine Arts", code: "MUS-CHOR-101" },
  { name: "Orchestra / Strings", department: "Fine Arts", code: "MUS-STR-101" },
  { name: "Theatre 1", department: "Fine Arts", code: "THE-101" },
  { name: "Theatre 2", department: "Fine Arts", code: "THE-102" },

  // --- CAREER & TECH (CATE) & ELECTIVES ---
  { name: "Personal Finance", department: "CATE", code: "BUS-101" },
  { name: "Fundamentals of Computing", department: "CATE", code: "CS-101" },
  { name: "AP Computer Science Principles", department: "CATE", code: "CS-501" },
  { name: "Entrepreneurship", department: "CATE", code: "BUS-102" },
  { name: "Marketing", department: "CATE", code: "BUS-103" },
  { name: "Sports Medicine 1", department: "CATE", code: "MED-101" },
  { name: "Agricultural Science", department: "CATE", code: "AG-101" },
  { name: "Intro to Horticulture", department: "CATE", code: "AG-102" },
  { name: "Family & Consumer Science", department: "CATE", code: "FCS-101" },

  // --- PE & JROTC ---
  { name: "PE 1: Personal Fitness", department: "PE", code: "PE-101" },
  { name: "Weight Training", department: "PE", code: "PE-102" },
  { name: "AFJROTC 1", department: "JROTC", code: "ROTC-101" },
  { name: "AFJROTC 2", department: "JROTC", code: "ROTC-102" },
];