import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Raleway } from "next/font/google";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const dynamic = "force-dynamic";

// Existing Geist fonts
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// New: Raleway + Poppins (must include weights)
const raleway = Raleway({
    variable: "--font-raleway",
    subsets: ["latin"],
    weight: ["400", "700"], // pick the weights you need
});

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400", "600"], // required: choose your weights
});

export const metadata: Metadata = {
    title: "Summit AI",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} ${poppins.variable}`}
        >
            <body className="antialiased">
                <Navbar />
                {children}
            </body>
        </html>
    );
}
