"use client";

import { useState, useTransition } from "react";
import { updateStudentProfile } from "@/app/actions/update-profile";
// We import the types generated by Prisma so TypeScript knows exactly what your DB looks like
import { Club, Sport, Course, Student } from "@prisma/client";

// Define a type that combines the Student data with their relations
type StudentWithRelations = Student & {
  clubs: Club[];
  sports: Sport[];
  courses: Course[];
};

type Props = {
  userId: string;
  student: StudentWithRelations;
  allClubs: Club[];
  allSports: Sport[];
  allCourses: Course[];
};

// We define a unified interface for the internal state so our table can handle all 3 types
interface SelectableItem {
  id: string;
  name: string;
  detail?: string | null; // This will hold 'category', 'season', or 'department'
}

export default function ProfileEditor({ 
  userId, 
  student, 
  allClubs, 
  allSports, 
  allCourses 
}: Props) {
  const [isPending, startTransition] = useTransition();

  // 1. Helper to convert DB objects (Club/Sport/Course) into our unified "SelectableItem" format
  // This allows us to store them all in the same kind of state arrays
  const formatItem = (item: Club | Sport | Course): SelectableItem => {
    let detail = "";
    if ("category" in item) detail = item.category;      // It's a Club
    else if ("season" in item) detail = item.season;     // It's a Sport
    else if ("department" in item) detail = item.department; // It's a Course
    
    return { id: item.id, name: item.name, detail };
  };

  // 2. Initialize State
  const [myClubs, setMyClubs] = useState<SelectableItem[]>(student.clubs.map(formatItem));
  const [mySports, setMySports] = useState<SelectableItem[]>(student.sports.map(formatItem));
  const [myCourses, setMyCourses] = useState<SelectableItem[]>(student.courses.map(formatItem));

  const [selectedClubId, setSelectedClubId] = useState("");
  const [selectedSportId, setSelectedSportId] = useState("");
  const [selectedCourseId, setSelectedCourseId] = useState("");

  // 3. Generic Add Helper
  const addItem = (
    id: string,
    sourceList: (Club | Sport | Course)[],
    currentList: SelectableItem[],
    setList: (items: SelectableItem[]) => void,
    resetSelection: (val: string) => void
  ) => {
    if (!id) return;
    
    const rawItem = sourceList.find((i) => i.id === id);
    if (!rawItem) return;

    // Check if already added
    if (!currentList.some((i) => i.id === id)) {
      setList([...currentList, formatItem(rawItem)]);
      resetSelection("");
    }
  };

  // 4. Generic Remove Helper
  const removeItem = (id: string, currentList: SelectableItem[], setList: (items: SelectableItem[]) => void) => {
    setList(currentList.filter((i) => i.id !== id));
  };

  const handleSubmit = (formData: FormData) => {
    startTransition(async () => {
      await updateStudentProfile(userId, formData);
    });
  };

  return (
    <div className="max-w-5xl mx-auto p-6">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">My Student Profile</h1>
        <p className="text-gray-600">Manage your academic details and extracurricular involvement.</p>
      </div>

      <form action={handleSubmit} className="space-y-8">
        
        {/* Hidden Inputs for Server Action */}
        {myClubs.map((item) => <input key={item.id} type="hidden" name="clubIds" value={item.id} />)}
        {mySports.map((item) => <input key={item.id} type="hidden" name="sportIds" value={item.id} />)}
        {myCourses.map((item) => <input key={item.id} type="hidden" name="courseIds" value={item.id} />)}

        {/* --- BASIC INFO --- */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
          <h2 className="text-xl font-semibold mb-4 border-b pb-2 text-gray-800">About Me</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-sm font-medium mb-1 text-gray-700">Current Grade Level</label>
              <select 
                name="gradeLevel" 
                defaultValue={student.gradeLevel || 9}
                className="w-full border p-2 rounded"
              >
                <option value="9">Freshman (9th)</option>
                <option value="10">Sophomore (10th)</option>
                <option value="11">Junior (11th)</option>
                <option value="12">Senior (12th)</option>
              </select>
            </div>
            <div className="md:col-span-2">
              <label className="block text-sm font-medium mb-1 text-gray-700">Bio</label>
              <textarea 
                name="bio" 
                defaultValue={student.bio || ""} 
                className="w-full border p-2 rounded h-24" 
                placeholder="Tell us about yourself..."
              />
            </div>
          </div>
        </div>

        {/* --- CLUBS --- */}
        <SectionTable 
          title="Clubs"
          items={myClubs}
          allRawItems={allClubs} // Pass the raw DB items here
          selectedId={selectedClubId}
          onSelect={setSelectedClubId}
          onAdd={() => addItem(selectedClubId, allClubs, myClubs, setMyClubs, setSelectedClubId)}
          onRemove={(id) => removeItem(id, myClubs, setMyClubs)}
          placeholder="Select a club to join..."
        />

        {/* --- SPORTS --- */}
        <SectionTable 
          title="Sports"
          items={mySports}
          allRawItems={allSports}
          selectedId={selectedSportId}
          onSelect={setSelectedSportId}
          onAdd={() => addItem(selectedSportId, allSports, mySports, setMySports, setSelectedSportId)}
          onRemove={(id) => removeItem(id, mySports, setMySports)}
          placeholder="Select a sport..."
        />

        {/* --- COURSES --- */}
        <SectionTable 
          title="Courses"
          items={myCourses}
          allRawItems={allCourses}
          selectedId={selectedCourseId}
          onSelect={setSelectedCourseId}
          onAdd={() => addItem(selectedCourseId, allCourses, myCourses, setMyCourses, setSelectedCourseId)}
          onRemove={(id) => removeItem(id, myCourses, setMyCourses)}
          placeholder="Select a course..."
        />

        {/* --- SAVE BUTTON --- */}
        <div className="fixed bottom-6 right-6 z-10">
          <button 
            type="submit" 
            disabled={isPending}
            className={`
              flex items-center gap-2 px-8 py-4 rounded-full font-bold shadow-xl transition-all
              ${isPending ? "bg-blue-400 cursor-not-allowed" : "bg-blue-700 hover:bg-blue-800 hover:scale-105 text-white"}
            `}
          >
            {isPending ? (
              <>
                <svg className="animate-spin h-5 w-5 text-white" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
                <span>Saving...</span>
              </>
            ) : (
              <>
                <span>Save Changes</span>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-5 h-5">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                </svg>
              </>
            )}
          </button>
        </div>

      </form>
    </div>
  );
}

// ---------------------------------------------------------
// REUSABLE TABLE COMPONENT (Strictly Typed)
// ---------------------------------------------------------

interface SectionTableProps {
  title: string;
  items: SelectableItem[]; // The items currently in the table
  allRawItems: (Club | Sport | Course)[]; // The full list from DB to choose from
  selectedId: string;
  onSelect: (id: string) => void;
  onAdd: () => void;
  onRemove: (id: string) => void;
  placeholder: string;
}

function SectionTable({ 
  title, 
  items, 
  allRawItems, 
  selectedId, 
  onSelect, 
  onAdd, 
  onRemove, 
  placeholder 
}: SectionTableProps) {
  
  // Filter out items that are already selected
  const availableItems = allRawItems.filter((raw) => !items.some((existing) => existing.id === raw.id));

  // Helper to get the display detail from a raw DB item for the dropdown
  const getDetail = (item: Club | Sport | Course) => {
    if ("category" in item) return item.category;
    if ("season" in item) return item.season;
    if ("department" in item) return item.department;
    return "";
  };

  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
      <h2 className="text-xl font-semibold mb-4 border-b pb-2 text-gray-800">{title}</h2>
      
      {/* Table of selected items */}
      {items.length > 0 ? (
        <div className="border rounded-lg overflow-hidden mb-4">
          <table className="w-full text-left">
            <thead className="bg-gray-50 text-gray-600 text-xs uppercase">
              <tr>
                <th className="px-4 py-3 font-medium">Name</th>
                <th className="px-4 py-3 font-medium">Details</th>
                <th className="px-4 py-3 text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {items.map((item) => (
                <tr key={item.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3 text-sm font-medium text-gray-900">{item.name}</td>
                  <td className="px-4 py-3 text-sm text-gray-500">{item.detail || "-"}</td>
                  <td className="px-4 py-3 text-right">
                    <button 
                      type="button"
                      onClick={() => onRemove(item.id)}
                      className="text-red-600 hover:text-red-800 text-sm font-medium"
                    >
                      Remove
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <p className="text-gray-500 text-sm italic mb-4">No {title.toLowerCase()} selected yet.</p>
      )}

      {/* Add new item controls */}
      <div className="flex gap-2">
        <select 
          value={selectedId} 
          onChange={(e) => onSelect(e.target.value)}
          className="flex-1 border border-gray-300 rounded-md p-2 text-sm"
        >
          <option value="">{placeholder}</option>
          {availableItems.map((item) => (
            <option key={item.id} value={item.id}>
              {item.name} ({getDetail(item)})
            </option>
          ))}
        </select>
        <button 
          type="button"
          onClick={onAdd}
          disabled={!selectedId}
          className="bg-gray-800 text-white px-4 py-2 rounded-md text-sm font-medium hover:bg-gray-900 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          Add {title.slice(0, -1)}
        </button>
      </div>
    </div>
  );
}